use std::env;
use std::fs;
use std::io::{Read, Result, Write};
use std::path::PathBuf;
use glob::glob;
use regex::Regex;

fn main() -> Result<()> {
    // 프로토 파일 찾기
    let proto_files: Vec<PathBuf> = glob("../../proto/**/*.proto")
        .expect("Failed to read glob pattern")
        .filter_map(|entry| entry.ok())
        .collect();

    //  컴파일
    prost_build::compile_protos(&proto_files, &["../../proto/"])?;

    // 패키지 이름 파싱 후 모듈 코드 자동 생성
    let package_regex = Regex::new(r"package\s+cortex\.(\w+);").unwrap();
    
    // 생성될 러스트 코드를 담을 버퍼
    let mut mod_code = String::new();
    mod_code.push_str("// 🤖 This file is AUTO-GENERATED by build.rs\n\n");

    // 중복 방지를 위한 Set (여러 파일이 같은 패키지를 쓸 수도 있으니)
    let mut generated_modules = std::collections::HashSet::new();

    for path in &proto_files {
        // 파일 내용 읽기
        let mut content = String::new();
        let mut file = fs::File::open(path)?;
        file.read_to_string(&mut content)?;

        // 패키지명 찾기
        if let Some(caps) = package_regex.captures(&content) {
            let module_name = caps.get(1).unwrap().as_str().to_string();

            // 아직 등록 안 된 모듈이면 코드 추가
            if !generated_modules.contains(&module_name) {
                let code = format!(
                    "pub mod {name} {{\n    include!(concat!(env!(\"OUT_DIR\"), \"/cortex.{name}.rs\"));\n}}\n\n",
                    name = module_name
                );
                mod_code.push_str(&code);
                generated_modules.insert(module_name);
            }
        }
        
        // 변경 감지 (재빌드 트리거)
        println!("cargo:rerun-if-changed={}", path.display());
    }

    // 생성된 코드를 OUT_DIR/protos_mod.rs 파일로 저장
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = PathBuf::from(out_dir).join("protos_mod.rs");
    let mut f = fs::File::create(&dest_path)?;
    f.write_all(mod_code.as_bytes())?;

    Ok(())
}